package br.com.mackenzie.view;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Tela.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//




public class Principal {
    public static void main(String[] args) {
        
    }
}
