package br.com.mackenzie.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Cliente.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//




public abstract class Cliente {
	protected String endereco;
	protected int telefone;
        
        public Cliente(String endereco, int telefone){
            
            this.endereco = endereco;
            this.telefone = telefone;
            
        }
        
        
	public void consultaCliente() {
            
            
            
	}
	
	public void cadastrarCliente() {
            
            
            
	}
        
        
}
