package br.com.mackenzie.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Fisico.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//




public class Fisico extends Cliente {
	private int CPF;
	private String nomeCompleto;
}
