package br.com.mackenzie.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Fornecedor.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//




public class Fornecedor {
	private String nomeFornecedor;
	private int tel;
	public void selecionarFornecedor() {
	}
	
	public void atualizarDados() {
	}
	
	public void excluirFornecedor() {
	}
	
	public void consultarFornecedor() {
	}
	
	public void incluirFornecedor() {
	}
}
