package br.com.mackenzie.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Juridico.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//
public class Juridico extends Cliente {
	private long CNPJ;
	private String nomeFantasia;

    public Juridico(String nomeFantasia, long CNPJ, String endereco, int telefone) {
        super(endereco, telefone);
        this.CNPJ = CNPJ;
        this.nomeFantasia = nomeFantasia;
    }

    public long getCNPJ() {
        return CNPJ;
    }

    public String getNomeFantasia() {
        return nomeFantasia;
    }        
    public void alterarDados(String nomeFantasia, long CNPJ,String endereco,int telefone){
        this.CNPJ = CNPJ;
        this.nomeFantasia = nomeFantasia;
        super.endereco = endereco;
        super.telefone = telefone;
    }

    @Override
    public String toString() {
        return "CNPJ = " + CNPJ + ", Nome Fantasia = " + nomeFantasia;
    }
    
    
}
