package br.com.mackenzie.model;

import java.util.Date;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Locacao.java
//  @ Date : 23/05/2016
//  @ Author : 
//
public class Locacao {
	private Date dataRetirada;
	private Date dataPrevista;
	private Date dataDevolucao;
	private double precoTotal;
	private double valorMulta;	
	
	public void calcularJuros() {}
	
	public void gerarValorPagar() {}
}
