package br.com.mackenzie.model;

//

import java.util.Date;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Produto.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//




public abstract class Produto {
	protected String modeloProduto;
	//protected SO sistemaOperacional;
	protected Date anoFabricacao;
	protected double telaPol;
	protected String telaResolucao;
	protected String fabricante;
	protected double precoPorDia;
	protected boolean statusAlugado;
	protected String acessorios;
	public void alterarStatusProduto(boolean status) {
	}
	
	public void visualizarProdutos() {
	}
	
	public void acrescentarProduto() {
	}
	
	public void alterarDadosProduto() {
	}
	
	public void excluirProduto() {
	}
	
	public void selecionarProduto() {
	}
}
