package br.com.mackenzie.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Smartphone.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//




public class Smartphone extends Produto {
	private double cameraResolucao;
	private char tipoRede;
	private boolean dualChip;
}
