package br.com.mackenzie.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Locacao
//  @ File Name : Tablet.java
//  @ Date : 23/05/2016
//  @ Author : 
//
//




public class Tablet extends Produto {
	private boolean camera;
	private boolean acessoRede;
}
